import os
import platform
import sys

def setup():
    print("--- BoothMachine Smart Screen Setup ---")
    print(f"OS: {platform.system()} {platform.release()}")
    
    print("Note: MAC address and IP will now be detected automatically at runtime.")
    
    api_host = input("Enter API Host [default: http://localhost]: ").strip()
    if not api_host:
        api_host = "http://localhost"
        
    api_port = input("Enter API Port [default: 4000]: ").strip()
    if not api_port:
        api_port = "4000"
        
    client_port = input("Enter Client Port [default: 3001]: ").strip()
    if not client_port:
        client_port = "3001"
        
    poll_interval = input("Enter Polling Interval (ms) [default: 30000]: ").strip()
    if not poll_interval:
        poll_interval = "30000"
        
    # 1. Write .env
    env_content = f"""# Generated by setup_device.py
NEXT_PUBLIC_API_HOST={api_host}
NEXT_PUBLIC_API_PORT={api_port}
# NEXT_PUBLIC_API_URL is optional, constructed in code if missing, or set here for compat
NEXT_PUBLIC_API_URL={api_host}:{api_port}
NEXT_PUBLIC_POLLING_INTERVAL={poll_interval}
PORT={client_port}
"""
    client_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    env_path = os.path.join(client_dir, '.env')
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    print(f"Successfully wrote config to {env_path}")

    # 2. Write start scripts
    # Windows .bat
    bat_content = f"""@echo off
echo Starting BoothMachine Client on port {client_port}...
cd /d "%~dp0"
call npm start -- -p {client_port}
pause
"""
    bat_path = os.path.join(client_dir, 'start_client.bat')
    with open(bat_path, 'w') as f:
        f.write(bat_content)
        
    # Linux .sh
    sh_content = f"""#!/bin/bash
DIR="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" && pwd )"
cd "$DIR"
echo "Starting BoothMachine Client on port {client_port}..."
npm start -- -p {client_port}
"""
    sh_path = os.path.join(client_dir, 'start_client.sh')
    with open(sh_path, 'w', newline='\n') as f:
        f.write(sh_content)
    
    # Make executable on linux (best effort from python)
    try:
        st = os.stat(sh_path)
        os.chmod(sh_path, st.st_mode | 0o111)
    except:
        pass

    print(f"Created startup scripts: start_client.bat (Windows), start_client.sh (Linux)")
    print("Setup complete.")

if __name__ == "__main__":
    setup()
